name: "push images on merge to master"

env:
  IMAGE_NAME: inspurwyd/${{ github.repository }}

on:
  push:
    branches:
      - master
jobs:
  build-and-push-amd64-ib-sriov-cni:
    name: image push amd64
    runs-on: ubuntu-22.04
    steps:
      - name: check out the repo
        uses: actions/checkout@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        run: |
            docker login -u zhugejingcheng  -p  1qaz@WSX quay.io

      - name: build and push ib-sriov-cni
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:latest-amd64
          file: ./Dockerfile
